# Pre-commit configuration
# Install: pre-commit install
# Update: pre-commit autoupdate

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  # Python formatting and linting
  # `pass_filenames: false` is necessary because changing a file can cause an unmodified file to have new issues.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        pass_filenames: false
      - id: ruff-format
        pass_filenames: false
        args: [ --check ]

  # Type checking
  # The official pre-commit hook does not use the uv-created environment.
  # `pass_filenames: false` is necessary because changing a file can cause an unmodified file to have new issues.
  - repo: local
    hooks:
      - id: mypy
        name: mypy type checker
        description: Type check Python files using mypy
        entry: uv run mypy .
        language: system
        pass_filenames: false
